name: Python Flask App CI

on:
  push:
    branches : ["*"]
  pull_request:
    branches : ["*"]
      

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.13.1  
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test.py 
